kubectl apply -f database-config.yaml
#kubectl apply -f database-migration-job.yaml
kubectl apply -f rabbitmq-config.yaml
kubectl apply -f api.yaml
kubectl apply -f api-service.yaml
kubectl apply -f consumer.yaml
kubectl apply -f consumer-service.yaml
kubectl apply -f ui.yaml
kubectl apply -f ui-service.yaml
kubectl apply -f nginx-ingress.yaml