apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: LoadBalancer
  ports:
  - port: 7778
    targetPort: 7778
    protocol: TCP
  selector:
    app: ui
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20