version: "3.4"

services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 7800:7800
    depends_on:
      - ui
      - api
    command: [nginx-debug, '-g', 'daemon off;']

  ui:
    build: ui
    image: ui
    restart: "no"
    # volumes:
    #   - ./ui/:/app
    ports:
      - 7778:7778
    depends_on:
      - api
    env_file:
      - project.env

  api:
    build: api
    image: api
    restart: "always"
    volumes:
      - ./api/:/app
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  consumer:
    build: consumer
    image: consumer
    container_name: consumer
    restart: "always"
    ports:
      - 7779:7779
    volumes:
      - ./consumer/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbitmq
      - api
    env_file:
      - project.env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: "always"
    ports:
      - 5672:5672
      - 15672:15672

  database:
    container_name: dab-p3-database-1e1d1527-f930-404d-9787-612b99e13eee
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  k6-stress-main:
    profiles: ["test"]
    image: grafana/k6
    command: ['run','--summary-trend-stats', 'min,avg,med,max,p(95),p(99),p(99.99)', 'benchmark.js']
    environment:
      - HOST=web
      - PORT=7800
    volumes:
      - ./tests/benchmark_main.js:/home/k6/benchmark.js

  k6-stress-message:
    profiles: ["test"]
    image: grafana/k6
    command: ['run','--summary-trend-stats', 'min,avg,med,max,p(95),p(99),p(99.99)', 'benchmark.js']
    environment:
      - HOST=web
      - PORT=7800
      - BHOST=api
      - BPORT=7777
    volumes:
      - ./tests/benchmark_message.js:/home/k6/benchmark.js

  k6-stress-add-message:
    profiles: ["test"]
    image: grafana/k6
    command: ['run','--summary-trend-stats', 'min,avg,med,max,p(95),p(99),p(99.99)', 'benchmark.js']
    environment:
      - HOST=api
      - PORT=7777
    volumes:
      - ./tests/benchmark_add_message.js:/home/k6/benchmark.js

  k6-stress-add-reply:
    profiles: ["test"]
    image: grafana/k6
    command: ['run','--summary-trend-stats', 'min,avg,med,max,p(95),p(99),p(99.99)', 'benchmark.js']
    environment:
      - HOST=api
      - PORT=7777
    volumes:
      - ./tests/benchmark_add_reply.js:/home/k6/benchmark.js
