version: "3.4"

services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 7800:7800
    depends_on:
      - ui
      - api
    command: [nginx-debug, '-g', 'daemon off;']

  ui:
    build: ui
    image: ui
    restart: "always"
    # volumes:
    #   - ./ui/:/app
    ports:
      - 7778:7778
    depends_on:
      - api
    env_file:
      - project.env

  api:
    build: api
    image: api
    restart: "always"
    volumes:
      - ./api/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  consumer1:
    build: grader
    image: grader
    container_name: grader1
    restart: "always"
    volumes:
      - ./grader/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbitmq
      - api
    env_file:
      - project.env

  consumer2:
    build: grader
    image: grader
    container_name: grader2
    restart: "always"
    volumes:
      - ./grader/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbitmq
      - api
    env_file:
      - project.env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: "always"
    ports:
      - 5672:5672
      - 15672:15672
    
  redis:
    image: redis:latest
    container_name: redis
    restart: "always"
    ports:
      - 6379:6379

  
  database:
    container_name: dab-p2-database-1e1d1527-f930-404d-9787-612b99e13eee
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:8.4.0-alpine
    container_name: flyway
    depends_on:
      - database
    volumes:
      - ./flyway/sql:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
  
  k6-stress-main:
    profiles: ["test"]
    image: grafana/k6
    command: ['run','--summary-trend-stats', 'min,avg,med,max,p(95),p(99),p(99.99)', 'benchmark.js']
    environment:
      - HOST=ui
      - PORT=7778
    volumes:
      - ./tests/benchmark_main.js:/home/k6/benchmark.js

  k6-stress-grade:
    profiles: ["test"]
    image: grafana/k6
    command: ['run','--summary-trend-stats', 'min,avg,med,max,p(95),p(99),p(99.99)', 'benchmark.js']
    environment:
      - HOST=api
      - PORT=7777
    volumes:
      - ./tests/benchmark_grade.js:/home/k6/benchmark.js

  grader-image:
    image: grader-image
    build: grader-image

  